apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user1-full-access-binding
  namespace: tancrede
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user1-full-access
subjects:
- kind: ServiceAccount
  name: user1
  namespace: tancrede
