apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-env
  labels:
    app: py-env
spec:
  replicas: 3
#  strategy:
#    type: Recreate
  selector:
    matchLabels:
      app: py-env
  template:
    metadata:
      labels:
        app: py-env
    spec:
      containers:
      - name: web
        image: tancou/py-env:1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: MA_DB_IP
            value: 'monip.local'
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: py-env-secret
                key: MON_SECRET
          - name: VARIABLE_1
            valueFrom:
              configMapKeyRef:
                name: py-env-cm
                key: variable1
        volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: py-env-cm
            items:
              - key: "monfichier.txt"
                path: "monfichier.txt"
