apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: py-env-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: py-env
 minReplicas: 3
 maxReplicas: 60
 targetCPUUtilizationPercentage: 50